---
title: "bs858_final"
author: "Michelle C. Hsu"
date: "December 4, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/Users/Michelle Hsu/Documents/bs858')
```

```{r}
library(dplyr)
```
```{r}
final<- read.csv("WABB_RV_and_sib_pheno_data.csv",header=T,as.is=T)
  dim(final)
  str(final)
  head(final, n = 20)
```
#Q1 heritability using ANOVA 
```{r}
#Heritability based on siblings (ANOVA) double check
kid1 = final[,c("famid","stdPET1")]
kid2 = final[,c("famid", "stdPET2")]

names(kid1) <- c("famid", "PET")
names(kid2) <- c("famid","PET")
kids <- rbind(kid1,kid2)

print(summary(aov(PET ~ as.factor(famid),data=kids)))

(1.2699-0.7302)/(1.2699 + (2-1)*0.7302)
2*0.2698365
```
#Q2 Dichotomous trait - familial
```{r}
#prevalence in my population
table(final$AD1) #292 is affected
292/nrow(final) # ~ 0.10
#prevalence of disease among sibs of affected 
sibs <- filter(final, final$AD1 == "2")
#print out sibs to check
table(sibs$AD2) #42 also affected in sib-pair
42/292 #~ 0.14 

#lamda rrisk
0.14/0.10
```
#Q3 HWE
```{r}
hwedat<- read.table("final_hwe.hwe",header=T,as.is=T)

filter(hwedat, hwedat$TEST == "ALL" & hwedat$P < 0.05)
id <-filter(hwedat, hwedat$TEST == "ALL")
```
#Q4
```{r}
q4<- read.table("final_freq.frq",header=T,as.is=T)
q4<-q4[c(15,11,6,14,10,16,5,13,4,7,8,9,12,1,2,3),] #re-order so that they are consistent in the order of the article for comparison.
q4_aq<- filter(q4,q4$MAF>0.05)
anti_join(q4, q4_aq, by = c("SNP" = "SNP"))
q4_aq$SNP

ave_3 <-  function(x, y,z){
  sum2<- sum(x,y,z,na.rm=T)
  return(sum2/3)
}
#use function to obtain average
YanMAF<-  c(
ave_3(0.20,0.21,0.28),
ave_3(0.43,0.44,0.43),
ave_3(0.45,0.42, 0.46),
ave_3(0.46, 0.49,0.50),
ave_3(0.42, 0.46, 0.47),
ave_3(0.23, 0.18, 0.19),
ave_3(0.12, 0.14, 0.12),
ave_3(0.30,0.31,0.33),
ave_3(0.21,0.20,0.22),
ave_3(0.07,0.06,0.06),
ave_3(0.06,0.08,0.04),
ave_3(0.10,0.11,0.09),
ave_3(0.34,0.34,0.36),
ave_3(0.13,0.15,0.17),
ave_3(0.19,0.16,0.21),
ave_3(0.07,0.07,0.08))
YanMAF <-as.data.frame(YanMAF)
compare<- cbind(q4$CHR, q4$SNP, q4$MAF,  YanMAF)
#the data I want to report my MAF
compare
filter(compare,compare$`q4$SNP`!= "rs200028958")
```
#Q5 See report

#Q6. genetic power calculation
#1-SD
```{r}
sd_units <-  function(x){
  return(x/0.4)
}

a<- c(0.18,-0.08,0.06,0.06,0.06,0.07,-0.08,-0.06,0.07,-0.18,0.11,0.10,-0.05,0.08,-0.07,0.16)
data<-as.data.frame(a)
data
# I happen to call this column 'a'
SD <- sd_units(data$a)

sddata<-cbind(q4,a, SD)
sddata
q<-1-sddata$MAF
q<-as.data.frame(q)
dat<-cbind(sddata, q)
#SD column - additive model 
```
#2-calculating h^2 (QTL)
```{r}
qtl_h2 <- (SD**2)*(2)*(dat$MAF)*(dat$q)
data<- as.data.frame(qtl_h2)
data
data6<- cbind(dat,data)

```
#Q7
```{r}
#linear.add.adjusted.assoc.linear
q7adjusted<- read.table("linear.add.adjusted.assoc.linear",header=T,as.is=T)


data<- filter(q7adjusted, q7adjusted$TEST == "COV3")

data_order<-data[c(15,11,6,14,10,16,5,13,4,7,8,9,12,1,2,3),] #re-order so that they are consistent in the order of the article for comparison.
data_order
#excluded: rs13260032, rs9831119, rs9531483,, rs11923588, rs4526799, rs62121100
```

#Q8c Find MAF and MB
```{r}
#in final dataset col 12 to 23 are all rare variants meaning MAF < 0.01
rare<-select(final, c(12:23))
rare


###  CMC with maf<=0.01 SNPs  ###
final$CMC<-apply(final[,12:23],1,sum)
table(final$CMC)
```
#Q8c Continue: Model - continuous outcome - gaussian
# for 8a as well
```{r}
## Analyses using PET amyloid deposition (logistic regression)
summary(glm(stdPET1 ~ age1 + sex1 + center1 + CMC, gaussian, final))
```
#9C
```{r}
#AD 1 is unaffected; 2 is affected
final$newAD1 <- ifelse(final$AD1 == 2 ,1,0)
table(final$newAD1)


summary(glm(newAD1~ age1 + sex1 + center1 + CMC, binomial("logit"), final))#not recommended - center1 is not statistically significant.
summary(glm(newAD1~ age1 + sex1 + CMC, binomial("logit"), final))#choice
```


